In [92]:
import pandas as pd
df = pd.read_csv('/Users/silas.rudolf/projects/School/MA/experiments/data/keyword-eval/scores.csv')
df

,filename,attention_max_precision@2,attention_max_precision@3,attention_max_precision@5,attention_max_rouge_1_r,attention_max_rouge_1_p,attention_max_rouge_1_f,attention_mean_precision@2,attention_mean_precision@3,attention_mean_precision@5,...,yake_precision@5,yake_rouge_1_r,yake_rouge_1_p,yake_rouge_1_f,frake_precision@2,frake_precision@3,frake_precision@5,frake_rouge_1_r,frake_rouge_1_p,frake_rouge_1_f
0,Bdb001.json_0,0.5,0.33,0.2,0.22,0.15,0.18,0.5,0.33,0.2,...,0.0,0.21,0.40,0.28,0.0,0.0,0.0,0.16,0.36,0.22
1,Bdb001.json_1,0.0,NaN,NaN,0.21,0.15,0.18,0.0,NaN,NaN,...,NaN,0.22,0.40,0.29,0.0,NaN,NaN,0.16,0.25,0.19
2,Bdb001.json_2,0.0,0.00,NaN,0.15,0.08,0.10,0.0,0.00,NaN,...,NaN,0.19,0.28,0.23,0.0,0.0,NaN,0.15,0.44,0.22
3,Bdb001.json_3,0.5,0.33,0.2,0.36,0.26,0.30,0.0,0.00,0.0,...,0.0,0.26,0.57,0.36,0.0,0.0,0.0,0.20,0.35,0.25
4,Bdb001.json_4,0.0,0.00,NaN,0.15,0.09,0.11,0.0,0.00,NaN,...,NaN,0.22,0.39,0.28,0.0,0.0,NaN,0.15,0.16,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892,education_9.json_1007,0.0,0.00,0.0,0.27,0.21,0.24,0.0,0.00,0.0,...,0.2,0.17,0.34,0.22,0.0,0.0,0.0,0.18,0.23,0.20
893,education_9.json_1008,0.5,0.33,0.2,0.30,0.34,0.32,0.5,0.33,0.2,...,0.0,0.17,0.52,0.25,0.0,0.0,0.0,0.16,0.52,0.24
894,education_9.json_1010,0.0,0.00,0.0,0.42,0.24,0.31,0.0,0.00,0.0,...,0.0,0.26,0.43,0.32,0.0,0.0,0.0,0.24,0.53,0.33
895,education_9.json_1011,0.0,0.00,NaN,0.25,0.24,0.25,0.0,0.00,NaN,...,NaN,0.24,0.36,0.29,0.0,0.0,NaN,0.27,0.55,0.37
896,education_9.json_1012,0.0,0.00,NaN,0.33,0.28,0.30,0.0,0.00,NaN,...,NaN,0.21,0.42,0.28,0.0,0.0,NaN,0.22,0.59,0.32

In [117]:
df.filter(regex=r'_precision@5').mean().sort_values(ascending=False)
#df[df.drop('filename', axis=1) >0 ].filter(regex=r'_precision@2').mean().sort_values(ascending=False)

keybert_default_precision@5    0.038000
keybert_mmr_precision@5        0.036667
attention_mean_precision@5     0.031333
attention_sum_precision@5      0.031333
attention_max_precision@5      0.026667
textrank_precision@5           0.018060
topicrank_precision@5          0.014765
positionrank_precision@5       0.014667
keybert_maxsum_precision@5     0.008247
frake_precision@5              0.007432
yake_precision@5               0.001333
rake_precision@5               0.000000
dtype: float64

In [122]:
df.filter(regex=r'_rouge_1_f').mean().sort_values(ascending=False)

keybert_default_rouge_1_f    0.327157
keybert_mmr_rouge_1_f        0.325619
yake_rouge_1_f               0.324983
topicrank_rouge_1_f          0.303924
positionrank_rouge_1_f       0.300569
textrank_rouge_1_f           0.293623
keybert_maxsum_rouge_1_f     0.270825
attention_mean_rouge_1_f     0.261628
attention_sum_rouge_1_f      0.260647
rake_rouge_1_f               0.257057
attention_max_rouge_1_f      0.250256
frake_rouge_1_f              0.242486
dtype: float64

In [77]:
import pandas as pd
df_batch = pd.read_csv('/Users/silas.rudolf/projects/School/MA/experiments/data/keyphrase-eval/batch_scores.csv')
df_full = pd.read_csv('/Users/silas.rudolf/projects/School/MA/experiments/data/keyphrase-eval/full_scores.csv')

In [78]:
df_batch

,filename,cnn_14000_rouge_1_mean_r,cnn_14000_rouge_1_mean_p,cnn_14000_rouge_1_mean_f,cnn_14000_rouge_1_max_r,cnn_14000_rouge_1_max_p,cnn_14000_rouge_1_max_f,cnn_35000_rouge_1_mean_r,cnn_35000_rouge_1_mean_p,cnn_35000_rouge_1_mean_f,...,xsum_10000_rouge_1_mean_f,xsum_10000_rouge_1_max_r,xsum_10000_rouge_1_max_p,xsum_10000_rouge_1_max_f,xsum_32000_rouge_1_mean_r,xsum_32000_rouge_1_mean_p,xsum_32000_rouge_1_mean_f,xsum_32000_rouge_1_max_r,xsum_32000_rouge_1_max_p,xsum_32000_rouge_1_max_f
0,Bdb001.json_0,0.500000,0.823569,0.612142,0.724138,1.000000,0.840000,0.568966,0.785051,0.609398,...,0.418436,0.827586,0.888889,0.857143,0.399015,0.865981,0.514314,1.000000,1.000000,1.000000
1,Bdb001.json_1,0.730769,0.500462,0.584589,1.000000,1.000000,1.000000,0.711538,0.471862,0.541436,...,0.537025,0.850000,0.708333,0.772727,0.730769,0.488970,0.547593,1.000000,1.000000,1.000000
2,Bdb001.json_2,0.587500,0.622326,0.586653,0.800000,0.826087,0.769231,0.552500,0.698381,0.608157,...,0.500698,0.900000,0.894737,0.627907,0.607500,0.667639,0.609950,1.000000,1.000000,1.000000
3,Bdb001.json_3,0.467611,0.767026,0.570674,0.653846,1.000000,0.680000,0.441296,0.730229,0.504356,...,0.475679,0.653846,1.000000,0.660194,0.410931,0.689515,0.477226,0.769231,0.833333,0.744681
4,Bdb001.json_4,0.437500,0.537194,0.475794,0.653846,0.750000,0.680000,0.644231,0.560236,0.575568,...,0.526803,0.884615,0.782609,0.734694,0.581731,0.629906,0.585861,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,education_9.json_1008,0.677632,0.650820,0.642235,0.982456,0.800000,0.727273,0.780702,0.621517,0.656739,...,0.642500,0.964912,0.809524,0.728477,0.635965,0.671798,0.639473,0.842105,0.860000,0.803738
1009,education_9.json_1009,0.712727,0.670181,0.657789,0.927273,0.848485,0.716418,0.594545,0.759084,0.622003,...,0.676649,0.890909,0.913043,0.824561,0.690909,0.836509,0.737803,1.000000,1.000000,1.000000
1010,education_9.json_1010,0.627312,0.702953,0.642271,0.905405,0.943396,0.787402,0.481508,0.754872,0.568316,...,0.657355,0.932432,0.916667,0.721311,0.539829,0.730465,0.592373,0.932432,0.884615,0.907895
1011,education_9.json_1011,0.822129,0.569149,0.629235,0.980392,0.875000,0.803738,0.738095,0.645484,0.626558,...,0.666448,0.980392,0.777778,0.793388,0.697479,0.714830,0.679884,0.980392,0.906250,0.787879
1012,education_9.json_1012,0.802381,0.574393,0.640563,0.964286,0.877551,0.819048,0.804762,0.619393,0.675843,...,0.690929,0.964286,0.886364,0.812500,0.764286,0.643038,0.665706,1.000000,1.000000,1.000000

In [79]:
df_batch.filter(regex=r'_mean_c').mean().sort_values(ascending=False)

xsum_32000_rouge_1_mean_f    0.609786
cnn_35000_rouge_1_mean_f     0.600843
cnn_14000_rouge_1_mean_f     0.592307
xsum_10000_rouge_1_mean_f    0.585372
dtype: float64

In [80]:
df_batch.filter(regex=r'_mean_p').mean().sort_values(ascending=False)

xsum_32000_rouge_1_mean_p    0.670201
cnn_35000_rouge_1_mean_p     0.636745
xsum_10000_rouge_1_mean_p    0.627487
cnn_14000_rouge_1_mean_p     0.620897
dtype: float64

In [81]:
df_batch.filter(regex=r'_mean_r').mean().sort_values(ascending=False)

cnn_35000_rouge_1_mean_r     0.690983
cnn_14000_rouge_1_mean_r     0.686113
xsum_32000_rouge_1_mean_r    0.660522
xsum_10000_rouge_1_mean_r    0.655755
dtype: float64

In [82]:
df_full

,filename,cnn_14000_rouge_1_r,cnn_14000_rouge_1_p,cnn_14000_rouge_1_f,cnn_35000_rouge_1_r,cnn_35000_rouge_1_p,cnn_35000_rouge_1_f,xsum_10000_rouge_1_r,xsum_10000_rouge_1_p,xsum_10000_rouge_1_f,xsum_32000_rouge_1_r,xsum_32000_rouge_1_p,xsum_32000_rouge_1_f
0,Bdb001.json_0,0.862069,1.000000,0.925926,1.000000,1.000000,1.000000,0.913793,0.981481,0.946429,1.000000,1.000000,1.000000
1,Bdb001.json_1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.600000,1.000000,0.750000,1.000000,1.000000,1.000000
2,Bdb001.json_2,0.775000,0.632653,0.696629,1.000000,1.000000,1.000000,0.775000,0.885714,0.826667,1.000000,1.000000,1.000000
3,Bdb001.json_3,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.288462,0.882353,0.434783,1.000000,1.000000,1.000000
4,Bdb001.json_4,0.846154,0.488889,0.619718,1.000000,1.000000,1.000000,0.423077,0.550000,0.478261,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,education_9.json_1008,0.877193,0.666667,0.757576,0.877193,0.666667,0.757576,0.947368,0.446281,0.606742,0.842105,0.827586,0.834783
1009,education_9.json_1009,0.854545,0.796610,0.824561,1.000000,1.000000,1.000000,0.854545,0.824561,0.839286,1.000000,1.000000,1.000000
1010,education_9.json_1010,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.594595,0.916667,0.721311,1.000000,1.000000,1.000000
1011,education_9.json_1011,0.980392,0.393701,0.561798,0.980392,0.471698,0.636943,0.980392,0.602410,0.746269,0.960784,0.680556,0.796748
1012,education_9.json_1012,0.714286,0.888889,0.792079,1.000000,1.000000,1.000000,0.678571,0.745098,0.710280,1.000000,1.000000,1.000000

In [85]:
df_full.filter(regex=r'_f').mean().sort_values(ascending=False)

xsum_32000_rouge_1_f    0.914947
cnn_35000_rouge_1_f     0.903947
cnn_14000_rouge_1_f     0.760504
xsum_10000_rouge_1_f    0.687051
dtype: float64

In [88]:
df_full.filter(regex=r'_p').mean().sort_values(ascending=False)

xsum_32000_rouge_1_p    0.916402
cnn_35000_rouge_1_p     0.900563
cnn_14000_rouge_1_p     0.757854
xsum_10000_rouge_1_p    0.732991
dtype: float64

In [90]:
df_full.filter(regex=r'1_r').mean().sort_values(ascending=False)

xsum_32000_rouge_1_r    0.935316
cnn_35000_rouge_1_r     0.934886
cnn_14000_rouge_1_r     0.824983
xsum_10000_rouge_1_r    0.721031
dtype: float64